PrestaShop/blockwishlist

js/ajax-wishlist.js

In Internet Explorer version 8 and older, having a property called "default" (technically a reserved word) defined as a bare word throws a syntax error and halts script execution. If you happen to be using CCC, this will break all Javascript on your entire site. Wrapping the property name in quotes fixes the issue.

[-] FO : Correct IE8 syntax error

---

.github/workflows/build-release.yml
.github/workflows/js.yml

| Description?  | Fix builds generating archives
| How to test?  | All the builds are green and the module archive can be used on a shop

Fix builds

---

controllers/front/view.php

| Description?  | Declare `$module` var as public in ProductListingController
| How to test?  | Having PsPixel and BlockWishlist does not trigger any issue
Fixing:

Make module prop public

---

blockwishlist.php
upgrade/upgrade-2.0.0.php

| Description?  | For merchants upgrading from PS 1.6, the module could not be used
| How to test?  | Install PrestaShop 1.6 and the blockwishlist module. Configure it for a user, then upgrade to PrestaShop 1.7. Uploading the latest module will set the new data for PS 1.7 and keep the existing wishlists.

Create database tables during upgrade from PS 1.6

---

.github/workflows/build-release.yml
.github/workflows/php.yml
classes/WishList.php

| Description?  | When a product inside a wishlist has been added to the cart, reset its quantity to 1 instead of zero.
| How to test?  | Adding a product in the cart from the wishlist page updates its quantity to 1.

Avoid negative or zero values as quantity

---

blockwishlist.php
classes/WishList.php

| Description?  | This PR fixes the value of ![image](https://user-images.githubusercontent.com/6768917/95361755-0d522980-08c5-11eb-9ef5-b6cb9c47d987.png) in the product lists, when using multishop.
| How to test?  | Even if we share products between shops in a multishop context, a product added in a shop should not have any impact on the other one.

Filter on current shop when displaying products in wishlist

---

blockwishlist.php

| Description?      | After merging #91, the tabs were not appearing anymore on the backoffice. This PR fixes the issue
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | /
| How to test?      | Pull this PR, resinstall the module and check the configuration page of wishlist. The tabs should be visible at the top of the page
| Possible impacts? | None

Update Parent tab to highlight Modules when on the configuration page

---

src/Search/WishListProductSearchProvider.php

| Description?      | Remove cover query for ps1770
| Fixed ticket?     | Fixes cover image when value is "0"
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

Remove cover query for ps1770

---

views/templates/hook/account/myaccount-block.tpl

| Description?      | Fix closing `a` tag
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24922
| How to test?      | Check that the tag is closed... Details in #122 
| Possible impacts? |

Fix closing 'a' tag, fixes #24922

---

_dev/front/js/components/Button/Button.vue
_dev/front/js/components/ChooseList/ChooseList.vue

| Description?      | Extends addedToWishlist event by data required to identify clearly added product
| How to test?      | Listen over `window.WishlistEventBus` and print params
| Possible impacts? | No one

Extend addedToWishlist by chosen product attribute id

---

_dev/front/scss/_product.scss
_dev/front/scss/_rtl.scss
_dev/front/scss/common.scss

| Description?      | Fixes RTL issues for add-to-wishlist button in product page and dropdown menu in list.
| Fixed ticket?     | Please see below
| How to test?      | Please see below
| Possible impacts? | RTL version of blockwishlist
**Product (RTL):**
Go to FO > Product page
The add-to-wishlist button has no margin next to the add-to-cart button.
**List (RTL):**
1. Go to FO > Product page
2. Select "Add to wishlist"
3. In modal window select "Create new list"
4. Go to FO > My Account > My wishlists 
There is an overflow for dropdown in mediem size screens.

Fixed RTL issues

---

src/Controller/WishlistConfigurationAdminController.php

| Description?      | Help sidebar was disabled on statistics page
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27134.
| How to test?      | Go on statistic page in the BO and try to click on the help button

Add help sidebar to the statistic page

---

views/templates/admin/home.html.twig
views/templates/admin/statistics.html.twig

| Description?      | card-block is not existing, it should be card-body
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/pull/25879#pullrequestreview-857500621.
| How to test?      | See issue, it's all about the configuration page markup
| Possible impacts? | configuration page

Refacto card-block to card-body

---

_dev/front/js/components/Toast/Toast.vue

| Description?      | Fix the width of toasts for theme-refacto.
| Fixed ticket?     | -
| How to test?      | https://github.com/PrestaShop/blockwishlist/pull/158#issuecomment-1017511633
| Possible impacts? | The blockwishlist alerts in theme-refacto (Doesn't impact on classic theme).
**Current:**
**Expected:**

Fix alert message width for theme-refacto

---

views/templates/pages/lists.tpl

| Description?      | Most of third-party themes (as like as theme-refacto) implements the account menu in "My Account" page. The blockwishlist should display this menu for list page. 
| Fixed ticket?     | -
| How to test?      | https://github.com/PrestaShop/blockwishlist/pull/157#issuecomment-1017442909
| Possible impacts? | The blockwishlist page in "My Account" (Doesn't impact classic theme).
**Current:**
**Expected:**

Make compatible with user account menu

---

views/templates/pages/products-list.tpl

| Description?      | Modals were imported 2 times in product list of wishlist
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27327.
| How to test?      | See issue
| Possible impacts? | Wishlist product list

Remove unneeded import in product list

---

blockwishlist.php
upgrade/upgrade-2.1.0.php

| Description?      | Removed the hook displayProductAdditionalInfo as the hook listener is not defined
| Fixed ticket?     | Relative to PrestaShop/PrestaShop#19230
| How to test?      | Install this branch<br>`blockwishlist` is not linked to the hook `displayProductAdditionalInfo`<br>In upgrade, the hook `displayProductAdditionalInfo` is unlinked.

Removed the hook displayProductAdditionalInfo as the hook listener is not defined

---

blockwishlist.php
controllers/front/lists.php
views/templates/hook/displayHeader.tpl
views/templates/pages/lists.tpl

| Description?      | When you go to your wishlist lists, when you click on create, it open 2 modals
| How to test?      | Go on my wishlist page and try to click on Create, then close the modal, it should works fine
| Possible impacts? | Wishlist page usage

Fix multiple modal open on wishlist list page

---

src/Search/WishListProductSearchProvider.php

| Description?      | When we have a restriction by productshown on wishlist view page the number of products that shows is not corect
| BC breaks?        |  no
| Deprecations?     |  no
| Ticket?      | Fixes https://github.com/PrestaShop/PrestaShop/issues/28164
| How to test?      | Go to the backoffice, configure the number of products to show in list, add more products in wishlist then that number, in list view yyou will see that the number of products in paginated in wrong way. See here https://drive.google.com/file/d/1lv2MVH6wTiH3reIKj-SHHHAMWMMvKViQ/view
| Possible impacts? | View wishlist page.

Number of products on wishlist page 

---

src/Calculator/StatisticsCalculator.php

| Description?      | Fetch the default picture if a product has no image defined
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#28131
| How to test?      | Cf. PrestaShop/PrestaShop#28131

Fetch the default picture if a product has no image defined

---

_dev/front/js/components/Create/Create.vue

| Description?      | In some occasions this modal it's on top of page, and cannot click on products, buttons....
| Type?             | bug fix 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28565
| How to test?      | Just check if modal create wish list its display block by default
PLEASE, I CANNOT TEST IT, BECAUSE I HAVE VS2022 AND THIS MODULE USES NODE-SASS V5 WHICH APART FROM Being DEPRECATED IT USES AN OLD NODE-GYP WHICH CANNOT RECOGNIZE VS2022 C++ BUILD TOOLS
ANYWAY, SUCH A SMALL CHANGE SHOULDN BE Too MUCH PROBLEM

Fix modal display block

---

config.xml

| Description?      | Use the good value for is_configurable
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28795
| How to test?      | Install a shop in french and compare config.xml and config_fr.xml 
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
If the value is 0, there will be no link to the module configuration when using `$module->is_configurable` via legacy
In any case the value is not good

Module is configurable

---

controllers/front/view.php
views/templates/errors/forbidden.tpl

| Description?      | Since PrestaShop/PrestaShop#27095, the `errors/forbidden.tpl` template has now content. As blockwishlist was using it, it now displays content as well. This PR fixes it by extending the core template and removing the content.
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#28832
| How to test?      | Please see PrestaShop/PrestaShop#28832
| Possible impacts? |

Remove forbidden error message from core template

---

src/Search/WishListProductSearchProvider.php

| Description?      | There was an issue when a product category belongs to multiple groups, it was duplicating the number of product in returned by the sql query.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29043
| How to test?      |  See the step in the parent issue
| Possible impacts? | On the list of products on the wishlist.

fix sql to get count or products

---

controllers/front/view.php
tests/phpstan.sh

| Description?      | Redirect to the homepage when trying to access an unauthorized wishlist with the correct error message
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29654.
| How to test?      | Try to access `/module/blockwishlist/view?id_wishlist=1` when being logged off
| Possible impacts? | The blockwishlist module

Fix for Behavior while logout on wishlist is not consistent

---

_dev/front/js/container/ProductsListContainer/ProductsListContainer.vue

| Description?      | Decrease min-width of select-list's wrapper to fit with narrower screens (768px down to 288px)
| Fixed ticket?     | Fixes PrestaShop/PrestaShop/issues/30070
| How to test?      | Apply PR changes.<br> In terminal rebuild assets.<br> In BO, Performance > Clear cache.<br> In FO, clear browser cache, then do check following the above issue's description.

Fix overflow filter select on small screens

---

.webpack/common.js
package.json

| Description?      | Fix: @babel/preset-env is not a plugin <br> Upgrade: webpack-cli from v3.3.10 to v4.3.1
| Type?             | bug fix / improvement
| Fixed ticket?     | check Description above i:)
| How to test?      | `npm install` && `npm run build` can complete without error.

Fix babel-loader options & Upgrade webpack-cli from v3.3 to v4.3

---

.github/workflows/build-release.yml

| Description?      | as recommended at https://github.com/PrestaShop/blockwishlist/actions/runs/4298859500 <br>_(using Organization Build Release Github Action at https://github.com/PrestaShop/blockreassurance/pull/521 does not fix the deprecated issue because Organization GH Action is also deprecated :)_
| Fixed ticket?     | See description above
| How to test?      | Automatic checks pass without warnings of Node 12 deprecation. <br>Artifact file can be created, downloaded, installed and work as usual.

Update build-release for Node14/16

---

.github/workflows/js.yml

| Description?      | Stop using deprecated https://github.com/PrestaShopCorp/github-action-lint-js
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| How to test?      | JS test run successfully without warning about deprecated github actions

Update github actions checkout and setup-node to v3

---

.github/workflows/php.yml

| Description?      | Update github actions checkout and cache from v2 to v3 to solve deprecated warnings.
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| How to test?      | PHP tests complete without warnings of deprecated github actions v2.

Update github actions checkout and cache from v2 to v3

---

blockwishlist.php
views/templates/components/modals/add-to-wishlist.tpl

| Description?      | Updated the code to get the default wishlist modal title from the configuration
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29212 (partially)
| How to test?      | Set  a default title in the configuration of the module in the backoffice, open the wishlist modal on a product page and check that the good title is shown.
| Possible impacts? | I don't think there is any impact.

Fix Issue : FO / Blockwishlist - Translations are not take in account for "Wishlist default title" part

---

.github/workflows/build-release.yml

| Description?      | Use npm ci instead of npm install
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | -

Use npm ci instead of npm install

---

upgrade/upgrade-0.3.0.php
upgrade/upgrade-1.1.0.php

| Description?      | Fix issues with upgrade file names. They could be executed by the core when not wanted.
| Fixed ticket?     | Problems found when testing upgrades of some modules.
| Sponsor company   | 
| How to test?      | No need.
| Current name | Correct name | What is wrong
| ------------------| ------------- | -------------
| blockwishlist\upgrade\upgrade-0.3.php | blockwishlist\upgrade\upgrade-0.3.0.php | Bad version format
| blockwishlist\upgrade\upgrade-1.1.php | blockwishlist\upgrade\upgrade-1.1.0.php | Bad version format

Standardize upgrade files

---

.github/workflows/ui-test.yml

| Description?      | UI Tests : Push to GCP<br><br>Big thanks to @boubkerbribri for the help on debugging.

UI Tests : Push to GCP

---

_dev/front/js/components/Product/Product.vue

| Description?      | Product buttons in wishlists didn't get proper labels and styling, because of invalid checks. `product.customizable` is an INT, not a STRING.
| Fixed ticket?     | Fixes #{issue URL here}, Fixes #{another issue URL here}
| How to test?      | 1. Add different products to your wishlist, including 1 out of stock and 1 customizable<br>2. Check your wishlist<br>3. Apply this PR and build assets<br>4. Check your wishlist again

Fix buttons on wishlist products

---

.github/workflows/ui-test.yml
Makefile

| Description?      | Migration from Docker Compose v1 to v2 (https://github.com/actions/runner-images/issues/9557)
| How to test?      | N/A

Migration from Docker Compose v1 to v2

---

src/Search/WishListProductSearchProvider.php

| Description?      | Removes meta_keywords that block https://github.com/PrestaShop/PrestaShop/pull/36873. This key is unused anway, all data is fetched by presenter.
| Type?             | refactor
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

Remove unused meta_keywords

---

src/Calculator/StatisticsCalculator.php

| Description?      | Fixed undefined array key category_name in statistics 
| Sponsor company   | PrestaShop SA 
| How to test?      | See https://github.com/PrestaShop/blockwishlist/pull/276#pullrequestreview-2275891782

Fixed undefined array key category_name in statistics

---

tests/UI/campaigns/02_configuration/02_statisticsTabSettings.spec.ts
tests/UI/package-lock.json

| Description?      | Functional Tests : Enable Tests after #280

Functional Tests : Enable Tests after #280
