PrestaShop/blockwishlist

WishList.php
blockwishlist.php

make the module config page to populate the select only with customers having a wishilist

[+] MO : Ease backoffice. Make the select show only customers having at least a wishlist

---

blockwishlist.tpl

"my wishlists" are not for crowlers ;)

[*] MO : blockwishlist : Added rel="nofollow"

---

blockwishlist.php

Fix notice on undefined variable

[-] MO : Fix notice on undefined variable

---

controllers/front/search.php
src/Search/WishListProductSearchProvider.php

Setup search to help @pablopolyte

Setup search provider and controller

---

controllers/front/search.php
src/Search/WishListProductSearchProvider.php

| Description?  | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?         | bug fix / improvement / new feature / refacto
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes {paste the issue here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

Search criteria

---

package-lock.json
upgrade/upgrade-2.0.0.php

| Description?  | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?         | bug fix / improvement / new feature / refacto
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes {paste the issue here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

Stat upgrade

---

classes/WishList.php
package-lock.json
upgrade/upgrade-2.0.0.php

| Description?  | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?         | bug fix / improvement / new feature / refacto
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes {paste the issue here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

Fixnbproductinwishlist

---

src/Search/WishListProductSearchProvider.php

| Description?  | Add product attribute to query and missing fields
| Type?         | improvement
| Fixed ticket? | 
| How to test?  | You should see all attributes and missing fields

Add product attribute to query and missing fields

---

.webpack/common.js
_dev/back/js/backoffice.js
_dev/back/scss/_stats.scss
config/routes.yml
src/Controller/WishlistConfigurationAdminController.php
src/Grid/Data/AllTimeStatisticsGridDataFactory.php
src/Grid/Data/BaseGridDataFactory.php
src/Grid/Data/CurrentDayStatisticsGridDataFactory.php
src/Grid/Data/CurrentYearStatisticsGridDataFactory.php
views/templates/admin/statistics.html.twig

:warning: Requires #52 to be merged first
| Description?  | Add a route to call via ajax to refresh the cache
| Type?         | new feature
| How to test?  | A clic on "Refresh cache" empties the cache then refreshes the statistics page

Add a route for cache refreshing

---

_dev/front/js/container/ProductsListContainer/ProductsListContainer.vue

| Description?  | Add the product listing feature
| Type?         |new feature
| How to test?  | Wishlist can be opened via id_wishlist, or token (sharing feature). Pagination and ordering is possible.

Add page to list products of a wishlist

---

blockwishlist.php
src/Database/Install.php
src/Grid/Data/CurrentMonthStatisticsGridDataFactory.php

| Description?  | Make PHPStan green
| How to test?  | PHPStan must be green prior merging

Fix PHPStan feedback

---

config/services.yml
src/Calculator/StatisticsCalculator.php

| Description?  | Allow price to be formatted on current context
| Type?         | improvement
| Fixed ticket? | 
| How to test?  | Refresh stats then check the price is formatted

Format price in statistics

---

_dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
_dev/front/js/container/ProductsListContainer/index.js
views/templates/pages/products-list.tpl

Add a message when there are no products in a wishlist

---

_dev/back/scss/_stats.scss
src/Grid/Definition/BaseStatisticsGridDefinitionFactory.php

Reduce lists images size

---

controllers/front/action.php
controllers/front/view.php
src/Access/CustomerAccess.php
src/Calculator/StatisticsCalculator.php

| Description?  | Check write permission on wishlists before altering them
| How to test?  | Other customers wishlists can't be modified, renamed or deleted

Assert write permission are given before altering lists

---

.webpack/common.js
_dev/back/js/backoffice.js
_dev/back/js/form.js
views/templates/admin/home.html.twig

Avoid javascript errors in BO

---

_dev/front/js/components/Product/Product.vue

Hover responsive

---

_dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
views/templates/pages/view.tpl

Delete unused filter button

---

_dev/front/js/components/Product/Product.vue
_dev/front/js/container/ProductsListContainer/ProductsListContainer.vue
config/services.yml
controllers/front/action.php
src/Access/CustomerAccess.php

| Description?  | Fix a call to a non-existing service on PS 1.7.6
| How to test?  | Using the module on PS 1.7.6 must work.
Fixed issue:

Fix unknown service on ps 1.7.6

---

.webpack/common.js
_dev/front/js/components/List/List.vue
_dev/front/js/components/Product/Product.vue
_dev/front/js/constants/headers.js
_dev/front/js/container/WishlistContainer/WishlistContainer.vue
_dev/front/js/graphql/resolvers.js

Some feedbacks from our PM

---

_dev/front/js/components/Product/Product.vue

Add quantity while adding to cart

---

blockwishlist.php
controllers/front/action.php
controllers/front/view.php
docker-compose.yml
src/Database/Install.php
src/Grid/Definition/AllTimeStatisticsGridDefinitionFactory.php
src/Grid/Definition/BaseStatisticsGridDefinitionFactory.php
src/Grid/Definition/CurrentDayStatisticsGridDefinitionFactory.php
src/Grid/Definition/CurrentMonthStatisticsGridDefinitionFactory.php
src/Grid/Definition/CurrentYearStatisticsGridDefinitionFactory.php
src/Search/WishListProductSearchProvider.php

:warning: Requires #68 to be merged first.
| Description?  | Replace `l()` with `trans()` to allow string to be exported on Crowdin
| How to test?  | /

Replace calls to l() with trans()

---

views/templates/components/pagination.tpl

Add placeholder instead of multiple i18n strings

---

controllers/front/view.php

Fix php translate typo

---

controllers/front/action.php

| Description?  | add id attribute verification before adding product to wishlist
| Type?         | code review
| BC breaks?    | nope
| Deprecations? | nope
| Fixed ticket? | Fixes {http://forge.prestashop.com/browse/EMKTG-208}.

add verification before adding product

---

src/Calculator/StatisticsCalculator.php
src/Grid/Definition/BaseStatisticsGridDefinitionFactory.php

| Description?  | Add a new field for combination in the stats grid
| Type?         |  improvement 
| Fixed ticket? | Fixes {http://forge.prestashop.com/browse/EMKTG-209}.

add combination field to stats grid

---

src/Calculator/StatisticsCalculator.php

| Description?  | Here we set a custom request for performance
| Type?         | improvement
| Fixed ticket? | Fixes {http://forge.prestashop.com/browse/EMKTG-210}.

switch the request

---

blockwishlist.php
controllers/front/action.php

| Description?  | set an event when a product is added to a wishlist, here we use hook
| Type?         |  new feature 
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | Fixes http://forge.prestashop.com/browse/EMKTG-192.

Add wl hook

---

blockwishlist.php
composer.json
config.xml
controllers/front/action.php
src/Calculator/StatisticsCalculator.php
src/Controller/WishlistConfigurationAdminController.php
src/Database/Install.php
src/Repository/WishlistRepository.php
src/Search/WishListProductSearchProvider.php

| Description?  | som fix after review
| Type?         | bug fix /refacto
| Deprecations? |  no

Fix changes requested

---

controllers/front/action.php

| Description?  | Rename a hook for the review

fix hook name

---

src/Calculator/StatisticsCalculator.php

| Description?  | fix sql syntax

add missing coma

---

src/Controller/WishlistConfigurationAdminController.php

| Description?  | Add the correct link for the sidebar menu
| Type?         | bug fix 

Fix the help link

---

classes/Statistics.php
controllers/front/action.php
src/Calculator/StatisticsCalculator.php
src/Database/Install.php
upgrade/upgrade-2.0.0.php

| Description?  | Here we set stats available for multistore
| Type?         | improvement 

set stats by shop id

---

controllers/front/lists.php

| Description?  |redirect to home after logout
| BC breaks?    |  no

Add a redirect to home is the user is not connected

---

config/services.yml
src/Controller/WishlistConfigurationAdminController.php
src/Grid/Data/AllTimeStatisticsGridDataFactory.php
src/Grid/Data/BaseGridDataFactory.php
src/Grid/Data/CurrentDayStatisticsGridDataFactory.php
src/Grid/Data/CurrentMonthStatisticsGridDataFactory.php
src/Grid/Data/CurrentYearStatisticsGridDataFactory.php

| Description?      | Adding shop id when save and delete cache.
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes QA

Fix stats cache per shop id

---

src/Controller/WishlistConfigurationAdminController.php
src/Grid/Data/BaseGridDataFactory.php
views/templates/admin/statistics.html.twig

| Description?      | add message when on multishop and fix error
| Type?             | bug fix / improvement

add a message and fix error when on multishop

---

views/templates/admin/statistics.html.twig

| Description?      | set is same as() instead of '===' in twig

set is same as

---

blockwishlist.php

| Description?      | Fixed call to vendor/autoload.php
| How to test?      | N/A
| Possible impacts? | N/A

Fixed call to vendor/autoload.php

---

blockwishlist.php

| Description?      | This Merge request gonna permit css override from a theme.
| Type?             | improvement 
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/24392
| How to test ? | Verify if blockwishlist functionalities works as usual (heart button, my wishlist pages...)
| Possible impacts? | None.

Change assets priorities to permit override

---

controllers/front/action.php

| Description?      | Fix an error in wording
| Fixed ticket?     | Related to https://github.com/PrestaShop/PrestaShop/pull/24449
| How to test?      | ~
| Possible impacts? | ~

Fix error in wording

---

blockwishlist.php
config.xml

| Description?      | Bump version 2.0.1
| Type?             | new feature
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

Bump version 2.0.1

---

upgrade/upgrade-2.0.0.php

| Description?      | Fix fatal error when upgrading from previous versions
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24321
| How to test?      | Upgrade from previous version should works without Exception
| Possible impacts? | Module upgrade

Fix upgrade from previous versions

---

blockwishlist.php
config.xml
upgrade/upgrade-2.1.0.php

| Description?      | Bump to 2.1.0

Bump to 2.1.0

---

views/templates/hook/displayHeader.tpl

| Description?      | Bundles were not present in some context and we're forced to add it on every pages because product list can be inside any hooks
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26853
| How to test?      | See isse
| Possible impacts? | Page sizeload

Add bundles on every context

---

src/Controller/WishlistConfigurationAdminController.php

| Description?      | There was no notification on save
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27128.
| How to test?      | Try to save the configuration form in the BO
| Possible impacts? | On save notification

Add flash notification on form save

---

classes/WishList.php

| Description?      | Fixed Number of Products in a WishList (if product is disabled or removed)
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27488
| How to test?      | Cf. PrestaShop/PrestaShop#27488

Fixed Number of Products in a WishList (if product is disabled or removed)

---

src/Controller/WishlistConfigurationAdminController.php

| Description?      | Fill empty config label by the label in default language
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#27474
| How to test?      | Cf. issue

Fill empty config label by the label in default language

---

blockwishlist.php
classes/Statistics.php
classes/WishList.php
upgrade/upgrade-2.1.0.php

| Description?      | Remove product from wishlist when the product (or the combination) is removed
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#28130
| How to test?      | Add product or combination to a wishlist<br>Delete the product or a combination from the backoffice<br>The statistics page runs well.

Remove product from wishlist when the product (or the combination) is removed

---

blockwishlist.php
config.xml

| Description?      | Bump version to 2.1.1
| How to test?      | 
| Possible impacts? |

Bump version to 2.1.1

---

blockwishlist.php
config.xml

| Description?      | Bump version to 2.1.2
| How to test?      | 
| Possible impacts? |

Bump version to 2.1.2

---

_dev/front/js/components/AddToWishlist/AddToWishlist.vue
_dev/front/scss/_modal.scss

| Description?      | Fix alignment in blockwishlist modals, title, description, field form and buttons
| Fixed ticket?     | Fixes [#29211](https://github.com/PrestaShop/PrestaShop/issues/29211)
| How to test?      | Follow issue
| Possible impacts? | ~

FO / Blockwishlist - Fix elements in modal not aligned on desktop & mobile screens

---

blockwishlist.php
config.xml

| Description?      | Bump version to 3.0.0
| BC breaks?        | yes
| How to test?      | N/A

Bump version to 3.0.0

---

blockwishlist.php
config.xml

| Description?      | ~
| Type?             | improvement 
| Fixed ticket?     | ~
| How to test?      | CI 🟢

Bump version to 3.0.1

---

blockwishlist.php
classes/Statistics.php
classes/WishList.php

| Description?      |  Attribute deletion fix, currently hook is not working properly Related to https://github.com/PrestaShop/PrestaShop/pull/32475
| How to test?      | Added product with specific attribute combination to wishlist and then delete that attribute in BO, then that product should be removed from wishlist as well

Attribute delete fix

---

blockwishlist.php
config.xml

| Description?      | Bump module version number.
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

Bump version number to 3.0.2

---

tests/UI/package-lock.json
tests/UI/package.json

| Description?      | Tests UI : Remove pwmochamesome dependency

Tests UI : Remove pwmochamesome dependency

---

.github/workflows/ui-test.yml

| Description?      | UI Tests : Add permissions

UI Tests : Add permissions

---

tests/UI/package-lock.json
tests/UI/package.json

| Description?      | UI Test : Remove duplicated dependencies
| Type?             | refactor

UI Tests : Remove duplicated dependencies

---

.github/workflows/ui-test.yml

| Description?      | UI Tests : Fixed output of the download-artifact

UI Tests : Fixed output of the download-artifact

---

.github/workflows/ui-test.yml
tests/UI/campaigns/02_configuration/02_statisticsTabSettings.spec.ts
tests/UI/package-lock.json
tests/UI/package.json

| Description?      | UI Tests : Bump `@prestashop-core/ui-testing` to 0.0.11

UI Tests : Bump `@prestashop-core/ui-testing` to 0.0.11

---

.github/workflows/ui-test.yml

| Description?      | UI Tests : Execute tests on 8.1.5

UI Tests : Execute tests on 8.1.5

---

.github/workflows/ui-test.yml

| Description?      | Functional Tests : Bump to PS8.1.6

Functional Tests : Bump to PS8.1.6

---

.github/workflows/ui-test.yml

| Description?      | Nightly : Bump to 8.1.6
| UI Tests          | 

Nightly : Bump to 8.1.6

---

tests/UI/campaigns/02_configuration/02_statisticsTabSettings.spec.ts
tests/UI/campaigns/02_configuration/04_helpHeaderButtons.spec.ts
tests/UI/package-lock.json
tests/UI/package.json
tests/UI/playwright.config.ts

| Description?      | Functional Tests : Wishlist module - Help header buttons
| UI Tests          | 

Functional Tests : Wishlist module - Help header buttons

---

.github/workflows/ui-test.yml
tests/UI/campaigns/03_frontOffice/01_lists/03_shareList.spec.ts
tests/UI/campaigns/03_frontOffice/02_products/01_addProductToList.spec.ts
tests/UI/package-lock.json

| Description?      | Functional Tests : Added 2 scenarios

Functional Tests : Added 2 scenarios

---

.github/workflows/ui-test.yml

| Description?      | Functional Tests : Fixed nightly

Functional Tests : Fixed nightly

---

.github/workflows/ui-test.yml
tests/UI/campaigns/01_installation/05_uninstallAndDeleteModule.spec.ts
tests/UI/docker-compose.yml
tests/UI/package-lock.json

| Description?      | Functional Tests : Added scenario "Uninstall and delete module"

Functional Tests : Added scenario "Uninstall and delete module"

---

tests/UI/package-lock.json

| Description?      | UI Tests : Bump `@prestashop-core/ui-testing`

UI Tests : Bump `@prestashop-core/ui-testing`

---

_dev/front/js/components/Button/Button.vue
tests/UI/campaigns/03_frontOffice/02_products/01_addProductToList.spec.ts

| Description?      | Fixed ability to mark a product (with specific combination) as favorite
| Type?             | bug fix 
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36593
| Sponsor company   | PrestaShop SA
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/36593 
The bug was introduced in this PR #212

Fixed ability to mark a product (with specific combination) as favorite
